[package]
name = "fluffy-octo-goggles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r2d2 = "0.8.9"
#r2d2-memcache = "0.6.0"
r2d2_redis = "0.14.0"
